code --install-extension abusaidm.html-snippets
code --install-extension aeschli.vscode-css-formatter
code --install-extension byCedric.vscode-expo
code --install-extension dbaeumer.vscode-eslint
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension eamodio.gitlens
code --install-extension ecmel.vscode-html-css
code --install-extension embertooling.prettier-for-handlebars-vscode
code --install-extension leveluptutorials.react-apollo-snippets
code --install-extension ms-vscode.cpptools
code --install-extension msjsdiag.vscode-react-native
code --install-extension PKief.material-icon-theme
code --install-extension ritwickdey.live-sass
code --install-extension ritwickdey.LiveServer
code --install-extension Shan.code-settings-sync
code --install-extension sibiraj-s.vscode-scss-formatter
code --install-extension sidthesloth.html5-boilerplate
code --install-extension syler.sass-indented
code --install-extension xabikos.JavaScriptSnippets
