import LocalizedStrings from 'react-localization';

const strings = new LocalizedStrings({
  "zh-hk": {
    homePage: "主頁",
    loanConfirmation: "貸款確認",
    acceptLoan: "接受貸款",
    apllyProgress: "貸款進度",
    accountOperations: "戶口操作",
    account: "戶口",
    submitFile: "提交文件",
    supplementaryFile: "補交文件",
    revolvingLoan: "循環貸款",
    prioritisedApproval: "優先批核",
    applyLoan: "申請貸款",
    applyNow: "立即申請",
    uploadFile: "補交文件",
    signContrat: "簽署合約",
    noContract: "找不到有效合約",
    setting: "設定",
    register: "登記",
    confirm: "確定",
    cancel: "取消",
    clear: "清除",
    done: "完成",
    submit: "提交",
    confirmSubmission: "確定提交",
    login: "登入",
    logout: "登出",
    username: "帳號",
    password: "密碼",
    googleVerifyCode: "Google驗證碼",
    rememberMe: "記住我的帳號",
    nextStep: "下一步",
    previousStep: "上一步",
    nextPage:"下一頁",
    previousPage:"上一頁",
    agreeAndContinue: "同意並繼續",
    continue: "繼續",
    goBack: "返回",
    confirmClose: "確定關閉?",
    confirmLogout: "確定登出?",
    preview: "預覽",
    selectFile: "選擇檔案",
    enterData: "請輸入資料",
    plsSelect: "請選擇",
    plsSubmitRelatedDoc: "請提交相關文件",
    clickToLoan: "一Click即借",
    loanApplication: "貸款申請",
    loan: "貸款",
    noLoan: "找不到有效貸款",
    loanApplicationForm: "貸款申請表",
    submitApplication: "提交表格",
    signature:"簽名",
    detail: "詳細",
    more: "更多",
    termsAndCondition: "條款及細則",
    totalAmount: "合計",
    amountCharged: "總金額",
    grandTotal: "總金額",
    homePageCenterBoxSlogan: "簡易快速完成貸款 網上一批即過數",
    bannerContent: "實時身份認證 全程極速辦妥",
    loanProduct: "貸款產品",
    applicationRequirements: "申請須知",
    loanWarning: "忠告:借錢梗要還 咪俾錢中介",
    statement: "聲明",
    contract: "合約",
    interestRate: "利率",
    startDate: "開始日期",
    totalPrincipal: "全期本金",
    lastTotalPrinciple: "已還本金",
    lastBalance: "尚欠本金",
    totalInterest: "全期利息",
    lastTotalInterest: "已還利息",
    outstandingInterest: "尚欠利息",
    lastTotalExtraCharge: "暫存金額",
    revolvingMaximumTerm: "循環貸款期數上限",
    revolvingAmount: "循環貸款上限",
    allowRevolving: "準許申請循環貸款",
    revolvingInterestRate: "循環貸年利率",
    isEarlyRepayment: "申請提還款",
    earlyRepaymentDate: "申請提還款",
    termsOfElectronicRegister: "電子登記條款和細則",
    dataUseStatement: "所有資料只作申請登記用途，本公司不會在沒有得到你的同意之下向任何第三方披露你的個人資料。",
    loanApplicationTOU: "本人確認為香港永久性居民並年齡為18歲或以上人士, 本人已詳細閱讀並同意放債人條例、私隱政策及收集個人資料聲明及私人貸款使用條約, 亦同意Credit KO Company Limited有權向任何第三方人士索取有關本人的資料, 包括向信貸資料機構查閱及提供本人的信貸記錄。",
    propertyType:"物業類型",
		propertyTypeOptions: {
			PRIVATE_HOUSING: "私人樓",
			APUBLIC_HOUSING: "公屋",
			HOME_OWNERSHIP_SCHEME: "居屋",
			VILLAGE_HOUSING: "村屋",
			QUARTERS: "宿舍",
			OTHERS : "其他"
		},
		propertyNature:"物業性質",
		propertyNatureOptions: {
			RENTAL: "租住物業",
			FAMILY_PROPERTY: "家人物業",
			SELF_OWNED: "自置物業",
		},
		livingWith: "與誰同住",
		livingWithOptions: {
			PARENTS:"父母",
			SIBLING:"兄第姐妹",
			SPOUSE:"配偶",
			CHILD:"子女",
			SELFONLY:"自住",
			OTHERS:"其他",
		}, 
		maritalStatus: "婚姻狀況",
		maritalStatusOptions: {
			SINGLE:"未婚",
			MARRIED:"已婚",
			DIVORCE:"離婚",
			WIDOWED:"喪偶",
		},
		companyName: "公司名稱",
		companyAddress: "公司地址",
		companyTel: "公司電話",
		employmentType: "受僱方式",
		employmentTypeOptions: {
			EMPLOYEE:"受僱",
			EMPLOYER:"自僱",
		},
    income: "每月收入",
		yearOfService: "服務年期",
		finanicalSituation: "總外債",
		livingYears: "居住年期",
    loanStepGuideScreen: {
      title: "申請流程",
      headContent: "立即申請 易借易還",
      scanIdCardAndFace: "掃描身份證和人面識別",
      applyAndVerify: "申請貸款 實時驗證身份",
      LoanApproval: "審批結果",
      instantCashTransfer: "貸款過數 現金到手",
      footerTitle: "一經批核 立即過數",
      getStarted: "立即開始",
    },
    termsOfRegisterScreen: {
      ordinanceTitle: "放債人條例條文撮要",
      ordinanceContent: `
      貸款協議的摘記或備忘錄所須
包括或附有的放債人條例條文撮要
以下所列的《放債人條例》(香港法例第163章) ("本條例") 條文撮要，對保障訂立貸款協議的各方均至為重要，應小心閱讀。該撮要並非法例的一部分，如有疑問，應參閱《放債人條例》有關條文。

本條例第III部撮要─放債人進行的交易

本條例第18條列出關於放債人作出貸款的規定。每份貸款協議須以書面訂立，並由借款人於該協議作出後的7天內及於該筆款項貸出之前簽署。在簽訂協議時，須將已簽署的一份協議摘記，連同本撮要一份給予借款人。該摘記須載有該宗貸款的詳盡細則，包括還款條款、保證形式及利率。不符合上述規定的協議不得予以強制執行，除非法庭信納不強制執行該協議並不公平。

本條例第19條訂定，如借款人提出書面要求及就有關開支而支付訂明費用，則放債人須將該借款人在貸款協議下當時的債務情況(包括已還款項、到期或即將到期的款項及利率)的結算書正本及副本一份給予借款人。借款人須在該結算書的副本上簽註文字，表示已經收到該結算書的正本，並將經如此簽註的該結算書副本交回該放債人。放債人則須在與該結算書有關的協議持續期間保留該份已交回的結算書副本。如放債人不照辦，即屬犯罪。如借款人提出書面要求，放債人亦須供給與該宗貸款有關或與保證有關的任何文件的副本。但上述要求，不得在一個月內提出超過一次。放債人如無充分理由而沒有遵照本段所述的要求辦理，則不得收取在該等要求沒有照辦期間的利息。

本條例第20條訂定，除非保證人亦是借款人，否則須在協議作出後的7天內，給予保證人一份已簽署的協議摘記、一份保證文書(如有的話)及詳列須支付款項總額的結算書。如保證人在任何時間提出書面要求(不得在一個月內超過一次)，放債人須給予他一份已簽署並詳列已支付款項總額及尚欠款項總額的結算書。放債人如無充分理由而沒有遵照辦理，則不得在該項要求沒有照辦期內強制執行該項保證。

本條例第21條訂定，借款人以書面通知後，可隨時將貸款及計算至還款日期為止的利息償還，放債人不得因借款人提早還款而徵收較高利率。

放債人如是財政司根據本條例第33A(4)條以憲報公告認可的放債人或認可的社團的成員，則上述條文不適用。

本條例第22條述明，任何貸款協議如訂定須支付複利或訂定不准以分期方式償還貸款，均屬非法。此外，任何貸款協議如訂定到期而未支付的款項須收取較高利率，亦屬非法，但該協議可訂定，未償還的本金部分及利息須收取單利，但利率不得超過在沒有拖欠的情況下須支付的利率；但如法庭信納，該協議如因不符合本條規定而成為非法並不公平，則可宣布該份非法協議全部或部分合法。

本條例第23條述明，如放債人在訂立貸款協議時或接受貸款保證時並未領有牌照，則與該放債人訂立的貸款協議及給予他的保證不得強制執行；但如法庭信納，該協議或保證如因本條規定而不能強制執行並不公平，則可宣布該協議或保證的全部或部分可予強制執行。

本條例第IV部撮要─過高利率

本條例第24條釐定任何貸款的最高實際利率為年息60%("實際利率"須按照本條例附表2計算)。任何貸款協議如訂定更高的實際利率，則不得強制執行，而放債人亦可被檢控。此最高利率可由立法會予以變更，但已存在的協議則不受影響。對於向繳足款股本不少於$1,000,000的公司作出的貸款或作出如此貸款的人，本條並不適用。

本條例第25條訂定，在強制執行貸款協議或強制執行貸款保證的法庭法律程序中，或在借款人本人或保證人本人向法庭申請濟助時，法庭可查察該協議的條款，以視該等條款是否極之不公平或利率過高(實際利率如超逾年息48%或立法會所訂的其他利率，即可單憑該理由而推定該利率過高)，而法庭在顧及所有情況後，可將該協議的條款更改，使其對協議各方均公平。對於向繳足款股本不少於$1,000,000的公司作出的貸款或作出如此貸款的人，本條並不適用。
      `
      ,
    },
    loanApplicationScreen: {
      myLoan: "我的貸款",
      date: "申請日期",
      loanID: "貸款編號",
      status: "申請狀態",
      viewContrat: "查看合約",
      provenFile: "證明文件",
      loanApplicationSubmissionDesc: `請確認資料正確，如資料錯誤將會影響審批時間。`
    },
    loanStatus: {
      REQUEST: "申請",
      WAIT_APPROVE: "待批核",
      APPROVED: "待申請人簽名",
      REJECTED: "已拒絕",
      MEMBER_CONFIRM: "已簽名",
      START: "生效中",
      FINISHED: "已完成",
      CANCELLED: "已取消",
      CUT_OFF: "已再融資",
      REVOLVING_PREVIEW: "審核中(循環貸款)",
      EARLY_REPAYMENT: "提早還款"
    },
    loanStatusCms: {
      REQUEST: "申請",
      WAIT_APPROVE: "待批核",
      APPROVED: "待申請人簽名",
      REJECTED: "已拒絕",
      MEMBER_CONFIRM: "申請人已簽名",
      START: "還款中",
      FINISHED: "已完成",
      CANCELLED: "已取消",
      CUT_OFF: "已再融資",
      REVOLVING_PREVIEW: "審核中(循環貸款)",
      EARLY_REPAYMENT: "提早還款"
    },
    loanStatusReport: {
      REQUEST: "申請中",
      WAIT_APPROVE: "待批核",
      APPROVED: "待申請人簽名",
      REJECTED: "已拒絕",
      MEMBER_CONFIRM: "申請人已簽名",
      START: "還款中",
      FINISHED: "已完成",
      CANCELLED: "已取消",
      CUT_OFF: "已再融資",
      REVOLVING_PREVIEW: "審核中(循環貸款)",
      EARLY_REPAYMENT: "提早還款"
    },
    repaymentType: "還款類型",
    repaymentTypeOptions: {
      REVOLVING: "循環貸款",
      REPAYMENT: '還款',
      EARLY_REPAYMENT: '提早還款',
      PATIAL_PRINCIPAL: '清還部分本金'
    },
    applyType: {
      NORMAL: "新貸款",
      REVOLVING: "循環貸款"
    },
    selectIDCardVersionScreen: {
      identityVerification: "身份驗證",
      headLine: "選擇香港身份證版本",
      headContent: "選擇你的身份證版本以進行身份驗證\n(只限年滿18歲或以上的香港居民)",
      oIDCard: "智能身份證",
      nIDCard: "新智能身份證",
      idCardVersion: "(x 版本)",
    },
    accountScreen: {
      creditLimit: "信貸額",
      currentLoan: "當前貸款",
      applyIncreaseCreditLimit: "申請提高信貸額",
      applyRevolvingLoan: "申請循環貸款",
      relatedDoc: "(稅單和入息證明)",
      settlementDate: "結單日",
      currentRepaymentAmount: "本期還款額",
      minimumRepayment: "最低還款額",
      submitRepaidProven: "提交還款證明"
    },
    submitRepaidProvenScreen: {
      header: "提交還款證明",
      desc: "(銀行轉帳紀錄)",
      RepaidProven: "還款證明"
    },
    phoneNumber: "電話號碼",
    inputYourPhoneNumber: "請輸入你的電話號碼",
    inputCorrectPhoneNumber: "請輸入正確電話號碼",
    verifyPhoneNumber: "電話號碼驗證",
    verifyCode: "驗證碼",
    resendVerifySmsCode: "重新發送SMS驗證碼",
    inputVerifySmsCode: "請輸入驗證碼",
    "sms.verify.smsInvalid": "驗證碼錯誤",
    "sms.verify.smsIn1min": "請等一分鐘後再試一次",
    agreeTOS: "我已閱讀並同意以上條款和政策",
    faceRecognization: "人面認證",
    tryAgain: "請重新再來一次",
    loading: "讀取中",
    personInfo: "個人資料",
    nameCht: "中文姓名",
    nameEn: "英文姓名",
    gender: "性別",
    genderM: "男",
    genderF: "女",
    hkid: "香港身份證號碼",
    dateOfBirth: "出生日期",
    fileIdProven: "身份證明",
    occupation: "職業",
    occupationCategory: "行業",
    occupationOptions: {},
    contactInfo: "聯絡資料",
    email: "Email",
    address: "住址",
    contactMethod: "聯絡方式",
    bestTimeContact: "方便聯絡的時間",
    bestTimeContactOptions: {
      "ANY":"任何",
      "AM09AM11":"9:00-11:00",
      "AM11PM13":"11:00-13:00",
      "PM13PM15":"13:00-15:00",
      "PM15PM17":"15:00-17:00",
      "PM17AFRER":"17:00之後"
    },
    fileAddressProven: "住址證明",
    nonBankrupt: "本人聲明本人現時並非破產或曾經破產人士， 而本人並無意申請破產及據本人所知現時並無任何有關本人破產呈請在進行中。",
    loanInfo:"貸款資料",
    requestAmount: "貸款",
    repaidAmount: "已還金額",
    approvalAmount: "批核金額",
    outstandingRepayment: "總欠款",
    apllyAmount: "申請金額",
    requestTotalTerms: "還款期",
    approvalTotalTerms: "批核還款期",
    repaidTerms:"已還款期數",
    outstandingRepaymentTerms: "尚欠還款期數",
    incomeMethod: "支薪方式",
    incomeMethodOptions: {
      AUTOPAY: "自動轉帳",
      CHEQUE: "支票",
      CASH: "現金"
    },
    requestType: "貸款類別",
    requestTypeOptions: {
      ONLINEQUICKTURNOVER: "網上特快周轉貸款",
      UNIVERSITY: "大學生貸款",
      BIGAMOUNTTRANSFER: "大額結餘轉戶",
      CIVILSERVENT: "公務員貸款",
      PROPERTYMORTGAGE: "物業按揭",
      BUSINESS_TURNOVER: "生意周轉",
      CAR_MORTGAGE: "購買汽車",
      MORTGAGE_FIRST: '樓宇按揭一按',
      MORTGAGE_SECOND: '樓宇按揭二按',
      PERSONAL_LOAN: "私人貸款",
      OTHERS: "其他"
    },
    bank: "銀行",
    bankCode: "銀行編號",
    bankAccount: "銀行戶口",
    bankAccountName: "戶口持有人姓名",
    bankAccountNumber: "戶口號碼",
    fps: "轉數快",
    fpsAccount: "轉數快識別碼",
    fpsTel: "轉數快電話號碼",
    fpsEmail: "轉數快電郵",
    bankOptions: {
      "003": "渣打銀行(香港)",
      "004": "香港上海滙豐銀行",
      "009": "中國建設銀行(亞洲)",
      "012": "中國銀行(香港)",
      "015": "東亞銀行",
      "016": "星展銀行(香港)",
      "018": "中信銀行(國際)",
      "020": "招商永隆銀行",
      "024": "恒生銀行",
      "025": "上海商業銀行",
      "028": "大眾銀行(香港)",
      "061": "大生銀行",
      "072": "中國工商銀行(亞洲)",
      "128": "富邦銀行(香港)",
      "250": "花旗銀行(香港)",
      "382": "交通銀行(香港)",
      "384": "摩根史坦利銀行(亞洲)"
    },
    fileIncomeProven: "收入證明",
    repaymentStatus: {
      repaid: "已還款",
      overdue: "逾期還款",
      unpaid: "待還款"
    },
    interestType: "計息方法",
    LoanInterestType: {
      'REDUCING_BALANCE': "息隨本減",
      'THE_RULE_OF_78': "78法則",
      'INTEREST_ONLY': "INTEREST_ONLY",
      'INTEREST_FIRST': "先息後本"
    },
    repaymentCycle: "還款週期",
    repaymentCycleOptions: {
      MONTH : '每月',
      MONTH_TWICE: '每月2次',
      BIWEEKLY: '每兩星期',
      DAY: '日數',
    },
    idCardDetection: {
      verifyIDCardFailed: "驗證身份證失敗",
      toofar: "太遠了",
      tooClose: "太近了",
      putOnCenter: "請把身分證放到鏡頭中間",
      turnFrontSide: "正面",
      turnUpSide: "向上轉",
      turnUpSideMore: "向上轉多一點",
      turnDownSide: "向下轉",
      turnDownSideMore: "向下轉多一點",
      turnLeft: "向左轉",
      turnLeftMore: "向左轉多一點",
      turnRight: "向右轉",
      turnRightMore: "向右轉多一點",
    },
    faceDetection: {
      blink: "請眨眼",
      turnHeadUp: "請抬頭",
      turnHeadDown: "請低頭",
      turnHeadLeft: "向左轉",
      turnHeadRight: "向右轉",
      NOD: "點頭",
      openMouth: "張開嘴",
      putFaceToCamera: "請把面部對準鏡頭",
      performActions: "請跟隨以下指示:"
    },
    langText: {
      "zh-hk": "英文",
      en: "中文"
    },
    dataTimePicker: {
      save: "儲存",
      selectSingle: "選擇日期",
      selectMultiple: "選擇日期",
      selectRange: "選擇日期",
      notAccordingToDateFormat: (inputFormat) =>
        `日期格式為 ${inputFormat}`,
      mustBeHigherThan: (date) => `請選${date}後的日期`,
      mustBeLowerThan: (date) => `請選${date}前的日期`,
      mustBeBetween: (startDate, endDate) =>
        `請選${startDate} - ${endDate}之間的日期`,
      dateIsDisabled: "禁用",
      previous: "上一頁",
      next: "下一頁",
      typeInDate: "日期格式",
      pickDateFromCalendar: "Calendar",
      close: "關閉",
    },
    filesPicker: {
      title: "按此上傳檔案或圖片",
      noFile: "沒有檔案"
    },
    contractScreen: {
      confirmSignture: "簽名確認",
      argeeContract: "我已閱讀並同意合約內容。",
      previewContract: "預覽合約"
    },
    error:{
      reqFailed: "請求失敗",
      sendFailed: "發送失敗",
      verifyFailed: "驗證失敗",
      inquireFailed: "查詢失敗",
      submitFailed: "提交失敗",
      loadPDFFailed: "讀取PFD失敗",
      loginFailed: "登入失敗",
      takePictureFailed: "拍照失敗"
    },
    inputError: {
      inputError: '輸入錯誤',
      pleCheckInput: "請檢查輸入是否正確",
      required: "*必填",
      requiredAge18: "必須年滿十八18歲",
      statementError: "必須同意已上聲明",
      email: "請輸入正確Email格式",
      interestRateMax: "年利率最高為48%",
    },
    noPermission: {
      camera: "使用相機權限不足",
      plsChangePermissionOnSetting: "請到設定緊改權限"
    },
    thankyou: {
      submitedFile: "已成功提交檔案",
      inProgres: "我們將會儘快為您處理"
    },
    userInfo: "個人資料",
    name: "名稱",
    permissions: "權限",
    role: "角色",
    permission: "權限",
    action: "操作",
    save: "儲存",
    createdAt: "建立",
    updatedAt: "更新",
    status: "狀態",
    active: "開通",
    deleted: "刪除",
    disableLogin: "禁止登入",
    isSuperAdmin: "系統管理員",
    increaseLimitStatus: {
      "REQUEST": "申請",
      "APPROVED": "批核",
      "REJECTED": "拒絕"
    },
    supplementaryDocumentType: {
      NA:"無",
      ID:"身份證明",
      ADDRESS:"地址證明",
      INCOME:"入息證明",
      BANK_STATEMENT: "銀行月結單"
    },
    receiptFileStatus: {
      SUBMIT:'已提交',
      APPROVED: '已查看',
      REJECTED: '已拒絕',   
    },
    earlyRepaymentStatus: {
      "REQUEST": "申請",
      "APPROVED": "批出申請",
      "REJECTED": "拒絕",
      "SUBMITED": "已提交還款證明",
      "FINISHED": "已完成"
    },
    bookKeepingPeriodOptions: { 
      "monthly": "每月",
      "weekly": "每週",
      "quarterly": "每3個月",
      "yearly": "每年"
    },
    bookKeepingPeriodInputOptions: { 
      "Monthly": "每月",
      "Weekly": "每週",
      "Quarterly": "每3個月",
      "Yearly": "每年"
    },
    bookKeepingPeriodDayOptions: {
      "32": "最後一日",
    },
    bookKeepingPeriodWeekOptions: { 
      "0": "星期日",
      "1": "星期1",
      "2": "星期2",
      "3": "星期3",
      "4": "星期4",
      "5": "星期5",
      "6": "星期6"
    },
    bookKeepingPeriodMonthOptions: {
      "1": "1月",
      "2": "2月",
      "3": "3月",
      "4": "4月",
      "5": "5月",
      "6": "6月",
      "7": "7月",
      "8": "8月",
      "9": "9月",
      "10": "10月",
      "11": "11月",
      "12": "12月",
    },
    week: "星期",
    month: "月",
    items: '項目',
    description: '描述',
    quantity: '數量',
    unitPrice: '單價',
    amount: '金額',
    total: '總計',
    subtotal: '小計',
    section: '項目',
  },
  en: {
    homePage: "Home",
    loanConfirmation: "Loan Confirmation",
    acceptLoan: "Accept Loan",
    apllyProgress: "Loan Progress",
    accountOperations: "Account",
    account: "Account",
    submitFile: "Submit File",
    supplementaryFile: "Supplementary File",
    revolvingLoan: "Revolving Loan",
    prioritisedApproval: "Prioritised Approval",
    applyLoan: "Apply Now",
    applyNow: "Apply Now",
    uploadFile: "Upload File",
    signContrat: "Sign Contrat",
    noContract: "There is no contract", 
    setting: "Setting",
    register: "Register",
    confirm: "Confirm",
    cancel: "Cancel",
    clear: "Clear",
    done: "Done",
    submit: "Submit",
    confirmSubmission: "Submission",
    login: "Login",
    logout: "Logout",
    username: "Username",
    password: "Password",
    googleVerifyCode: "Google Verify Code",
    rememberMe: "rememberMe",
    nextStep: "Next",
    previousStep: "Previous",
    nextPage:"Next",
    previousPage:"Previous",
    agreeAndContinue: "Agree and Continue",
    continue: "Continue",
    goBack: "Go Back",
    confirmClose: "Confirm Close?",
    confirmLogout: "Confirm Logout?",
    preview: "Preview",
    selectFile: "Select File",
    enterData: "Please enter information",
    plsSelect: "Please select",
    plsSubmitRelatedDoc: "Please submit relevant documents",
    clickToLoan: "Click To Loan",
    loan: "Loan",
    noLoan: "There is no loan",
    loanApplication: "Loan Application",
    loanApplicationForm: "Loan Application",
    submitApplication: "Submition",
    signature:"Signature",
    detail: "Detail",
    more: "More",
    termsAndCondition: "Terms and Conditions",
    totalAmount: "Total Amount",
    amountCharged: 'Amount Charged',
    grandTotal: "Grand Total",
    homePageCenterBoxSlogan: "Easy and fast loan completion",
    bannerContent: "Express application\nprocess with ID verifcation",
    loanProduct: "Loan Product",
    applicationRequirements: "Application Requirements",
    loanWarning: "Warning: You have to repay your loans.\nDon't pay any intermediaries",
    statement: "Statement",
    contract: "Contract",
    interestRate: "Interest Rate",
    startDate: "startDate",
    totalPrincipal: "totalPrincipal",
    lastTotalPrinciple: "lastTotalPrinciple",
    lastBalance: "lastBalance",
    totalInterest: "totalInterest",
    lastTotalInterest: "lastTotalInterest",
    outstandingInterest: "outstandingInterest",
    lastTotalExtraCharge: "lastTotalExtraCharge",
    termsOfElectronicRegister: "Terms and Conditions For Electronic Registration",
    dataUseStatement: "All information is only used for registration application, We will not disclose your personal information to any third party without your consent.",
    loanApplicationTOU: "I confirm that I am a Hong Kong permanent resident and am 18 years old or above, I have read and agree to the Money-lenders Ordinance, Privacy Policy and Personal Information Collection Statement and Personal Loan Terms of Use, and I also agree that Credit KO Company Limited has the right to provide any Requests by third parties for information about me, including access to and provision of my credit history to credit reference agencies.",
    propertyType:"物業類型",
		propertyTypeOptions: {
			PRIVATE_HOUSING: "私人樓",
			APUBLIC_HOUSING: "公屋",
			HOME_OWNERSHIP_SCHEME: "居屋",
			VILLAGE_HOUSING: "村屋",
			QUARTERS: "宿舍",
			OTHERS : "其他"
		},
		propertyNature:"物業性質",
		propertyNatureOptions: {
			RENTAL: "租住物業",
			FAMILY_PROPERTY: "家人物業",
			SELF_OWNED: "自置物業",
		},
		livingWith: "與誰同住",
		livingWithOptions: {
			PARENTS:"父母",
			SIBLING:"兄第姐妹",
			SPOUSE:"配偶",
			CHILD:"子女",
			SELFONLY:"自住",
			OTHERS:"其他",
		}, 
		maritalStatus: "婚姻狀況",
		maritalStatusOptions: {
			SINGLE:"未婚",
			MARRIED:"已婚",
			DIVORCE:"離婚",
			WIDOWED:"喪偶",
		},
		companyName: "公司名稱",
		companyAddress: "公司地址",
		companyTel: "公司電話",
		employmentType: "工作類型",
		employmentTypeOptions: {
			EMPLOYEE:"受僱",
			EMPLOYER:"自僱",
		},
		yearOfService: "服務年期",
		finanicalSituation: "總外債",
		livingYears: "居住年期",
    loanStepGuideScreen: {
      title: "Application Steps",
      headContent: "Loan application with instant ID verification",
      scanIdCardAndFace: "Scand ID card and face",
      applyAndVerify: "Loan appplication with\n instant ID verification",
      LoanApproval: "Loan approval",
      instantCashTransfer: "Instant cash transfer",
      footerTitle: "Transfer immediately after approval",
      getStarted: "Get Started"
    },
    termsOfRegisterScreen: {
      ordinanceTitle: "Summary of Provisions of The money Lenders Ordinance",
      ordinanceContent: `SUMMARY OF PROVISIONS OF THE MONEY LENDERS
      ORDINANCE TO BE INCLUDED IN OR ATTACHED TO A NOTE OR
      MEMORANDUM OF A LOAN AGREEMENT
      The provisions of the Money Lenders Ordinance (Cap.163 of Laws of Hong Kong) (the "Ordinance") summarised below are important for the protection of all the parties to a loan agreement, and should be read carefully. The summary is not part of the law, and reference should be made to the provisions of the Ordinance itself in case of doubt.
      
      Summary of Part III of the Ordinance-Money lenders transactions
      
      Section 18 sets out the requirements relating to loans made by a money lender. Every agreement for a loan must be put into writing and signed by the borrower within 7 days of making the agreement and before the money is lent. A copy of the signed note of the agreement must be given to the borrower, with a copy of this summary, at the time of signing. The signed note must contain full details of the loan, including the terms of repayment, the form of security and the rate of interest. An agreement which does not comply with the requirements will be unenforceable, except where a court is satisfied that it would be unjust not to enforce it.
      
      Section 19 provides that a money lender must, if requested in writing and on payment of the prescribed fee for expenses, give the original and a copy of a written statement of a borrower"s current position under a loan agreement, including how much has been paid, how much is due or will be due, and the rate of interest. The borrower must endorse on the copy of the statement words to the effect that he has received the original of the written statement and return the copy as so endorsed to the money lender. The money lender must retain the copy of the statement so returned during the continuance of the agreement to which that statement relates. If the money lender does not do so he commits an offence. The money lender must also, upon a request in writing, supply a copy of any document relating to the loan or security. But a request cannot be made more than once per month. Interest is not payable for so long as the money lender, without good reason, fails to comply with any request mentioned in this paragraph.
      
      Section 20 provides that the surety, unless he is also the borrower, must within 7 days of making the agreement be given a copy of the signed note of the agreement, a copy of the security instrument (if any) and a statement with details of the total amount payable. The money lender must also give the surety, upon request in writing at any time (but not more than once per month) a signed statement showing details of the total sum paid and remaining to be paid. The security is not enforceable for so long as the money lender, without good reason, fails to comply.
      
      Section 21 provides that a borrower may at any time, on giving written notice, repay a loan together with interest to the date of repayment, and no higher rate of interest may be charged for early repayment.
      
      This provision, however, will not apply where the money lender is recognized, or is a member of an association recognized, by the Financial Secretary by notice in the Gazette in force under section 33A(4) of the Ordinance.
      
      Section 22 states that a loan agreement is illegal if it provides for the payment of compound interest, or provides that a loan may not be repaid by instalments. A loan agreement is also illegal if it charges a higher rate of interest on amounts due but not paid, although it may provide for charging simple interest on that part of the principal and interest outstanding at a rate not exceeding the rate payable apart from any default. The illegal agreement may, however, be declared legal in whole or in part by a court if the court is satisfied that it would be unjust if the agreement were illegal because it did not comply with this section.
      
      Section 23 declares that a loan agreement with a money lender and any security given for the loan will not be enforceable if the money lender was unlicensed at the time of making the agreement or taking the security. The loan agreement or security may, however, be declared enforceable in whole or in part by a court if the court is satisfied that it would be unjust if the agreement or security were unenforceable by virtue of this section.
      
      Summary of Part IV of the Ordinance-Excessive interest rates
      
      Section 24 fixes the maximum effective rate of interest on any loan at 60% per annum (the "effective rate" is to be calculated in accordance with the Second Schedule to the Ordinance). A loan agreement providing for a higher effective rate will be unenforceable and the lender will be liable to prosecution. This maximum rate may be changed by the Legislative Council but not so as to affect existing agreements. The section does not apply to any loan made to a company which has a paid up share capital of not less than $1,000,000 or, in respect of any such loan, to any person who makes that loan.
      
      Section 25 provides that where court proceedings are taken to enforce a loan agreement or security for a loan or where a borrower or surety himself applies to a court for relief, the court may look at the terms of the agreement to see whether the terms are grossly unfair or exorbitant (an effective rate of interest exceeding 48% per annum or such other rate as is fixed by the Legislative Council, may be presumed, on that ground alone, to be exorbitant), and, taking into account all the circumstances, it may alter the terms of the agreement in such a manner as to be fair to all parties. The section does not apply to any loan made to a company which has a paid up share capital of not less than $1,000,000 or, in respect of any such loan, to any person who makes that loan.`
      ,
    },
    loanApplicationScreen: {
      myLoan: "My Loan",
      date: "Application Date",
      loanID: "Loan ID",
      status: "Loan Status",
      viewContrat: "View Contrat",
      provenFile: "Documents",
      loanApplicationSubmissionDesc: `Confirm that the information is correct, if the information is wrong, it will affect the approval time. After submitting.`
    },
    loanStatus: {
      REQUEST: "Submited",
      WAIT_APPROVE: 'WAIT_APPROVE',
      APPROVED: "Pending Signature",
      REJECTED: "Rejected",
      MEMBER_CONFIRM: "Signature",
      START: "Started",
      FINISHED: "Finished",
      CANCELLED: "Cancelled",
      CUT_OFF: "CUT_OFF",
      REVOLVING_PREVIEW: "Processing"
    },
    loanStatusCms: {
      REQUEST: "REQUEST",
      APPROVED: "APPROVED",
      REJECTED: "REJECTED",
      MEMBER_CONFIRM: "MEMBER_CONFIRM",
      START: "START",
      FINISHED: "FINISHED",
      CANCELLED: "CANCELLED",
      CUT_OFF: "CUT_OFF",
      REVOLVING_PREVIEW: "REVOLVING_PREVIEW"
    },
    applyType: {
      NORMAL: "NORMAL",
      REVOLVING: "REVOLVING"
    },
    selectIDCardVersionScreen: {
      identityVerification: "Identity Verification",
      headLine: "Select HKID Card Version",
      headContent: "Select HKID card version for identity\n(Hong Kong residents aged 18 or above only)",
      oIDCard: "Smart ID Card",
      nIDCard: "New Smart ID Card",
      idCardVersion: "(x Version)",
    },
    accountScreen: {
      creditLimit: "Credit Limit",
      currentLoan: "Current Loan",
      applyIncreaseCreditLimit: "Increase Credit Limit",
      applyRevolvingLoan: "Revolving Loan",
      relatedDoc: "(tax bill and proof of income)",
      settlementDate: "Settlement Date",
      currentRepaymentAmount: "Repayment Amount",
      minimumRepayment: "Minimum Repayment",
      submitRepaidProven: "Submit Repaid Proven"
    },
    submitRepaidProvenScreen: {
      header: "Submit Repaid Proven",
      title: "Please submit relevant documents",
      desc: "(Bank transfer record)",
      RepaidProven: "Repaid Proven"
    },
    phoneNumber: "Phone Number",
    inputYourPhoneNumber: "Input Your Phone Number",
    inputCorrectPhoneNumber: "Input Correct Phone Number",
    verifyPhoneNumber: "Verify Phone Number",
    verifyCode: "Verify Code",
    resendVerifySmsCode: "Resend Verify SMS Code",
    inputVerifySmsCode: "Input Verify SMS Code",
    "sms.verify.smsInvalid": "Verify SMS Code Invalid",
    "sms.verify.smsIn1min": "Please try again after 1 minite",
    agreeTOS: "I has readed and agree that policy and terms",
    faceRecognization: "Face Recognization",
    tryAgain: "Try again",
    loading: "Loading",
    personInfo: "Person Info",
    nameCht: "Chinese Name",
    nameEn: "English Name",
    gender: "Gender",
    genderM: "Male",
    genderF: "Female",
    hkid: "Hong Kong ID",
    dateOfBirth: "Date Of Birth",
    fileIdProven: "ID Card Proven",
    occupation: "Occupation",
    occupationCategory: "occupationCategory",
    occupationOptions: {},
    contactInfo: "Contact Info",
    email: "Email",
    address: "Address",
    contactMethod: "Contact Method",
    bestTimeContact: "Best Time Contact",
    bestTimeContactOptions: {
      "ANY": "Any",
      "AM09AM11": "9:00-11:00",
      "AM11PM13": "11:00-13:00",
      "PM13PM15": "13:00-15:00",
      "PM15PM17": "15:00-17:00",
      "PM17AFRER": "After 17:00"
    },
    fileAddressProven: "Address Proven",
    loanInfo: "Loan Info",
    nonBankrupt: "I declare that I have not been delinquent in repaying any credit facilities with any financial institution. I am not bankrupt or a discharged bankrupt, have no intention to declare bankruptcy, and am not aware of any bankruptcy proceedings made against me.",
    requestAmount: "Request Amount",
    repaidAmount: "Total Repaid",
    approvalAmount: "Approval Amount", 
    outstandingRepayment: "Outstanding Amount",
    apllyAmount: "Aplly Amount",
    requestTotalTerms: "Total Terms",
    approvalTotalTerms: "Approval Terms",
    repaidTerms: "Repaid Terms",
    outstandingRepaymentTerms: "Outstanding Terms",
    incomeMethod: "Incom Method",
    incomeMethodOptions: {
      AUTOPAY: "Automatic Transfers",
      CHEQUE: "Cheque",
      CASH: "Cash"
    },
    requestType: "Loan Type",
    requestTypeOptions: {
      ONLINEQUICKTURNOVER: "Online Express Revolving Loan",
      UNIVERSITY: "Student Loan",
      BIGAMOUNTTRANSFER: "Big Amount Transfer",
      CIVILSERVENT: "Civil Servant Loan",
      PROPERTYMORTGAGE: "Mortgage",
      BUSINESS_TURNOVER: "BUSINESS_TURNOVER",
      CAR_MORTGAGE: "CAR_MORTGAGE",
      OTHERS: "OTHERS"
    },
    bank: "Bank",
    bankAccount: "Bank Account",
    bankCode: "bankCode",
    bankAccountName: "Bank Account Name",
    bankAccountNumber: "Bank Account Number",
    fpsAccount: "fpsAccount",
    fpsTel: "fpsTel",
    fpsEmail: "fpsEmail",
    bankOptions: {
      "003": "Standard Chartered Bank (Hong Kong)",
      "004": "The Hongkong and Shanghai Banking Corporation",
      "009": "China Construction Bank (Asia)",
      "012": "Bank of China (Hong Kong)",
      "015": "The Bank of East Asia",
      "016": "DBS Bank (Hong Kong)",
      "018": "China CITIC Bank International",
      "020": "CMB Wing Lung Bank",
      "024": "Hang Seng Bank",
      "025": "Shanghai Commercial Bank",
      "028": "Public Bank (Hong Kong)",
      "061": "Tai Sang Bank",
      "072": "Industrial and Commercial Bank of China (Asia)",
      "128": "Fubon Bank (Hong Kong)",
      "250": "Citibank (Hong Kong)",
      "382": "Bank of Communications (Hong Kong)",
      "384": "Morgan Stanley Bank Asia"
    },
    fileIncomeProven: "Income Proven",
    repaymentStatus: {
      repaid: "Repaid",
      overdue: "Overdue",
      unpaid: "Unpaid"
    },
    idCardDetection: {
      verifyIDCardFailed: "Verify ID Card Failed",
      toofar: "Too Far",
      tooClose: "Too Close",
      putOnCenter: "Put On Center",
      turnFrontSide: "Front Side",
      turnUpSide: "Turn Up",
      turnUpSideMore: "Turn Up More",
      turnDownSide: "Turn Down ",
      turnDownSideMore: "Turn Down More",
      turnLeft: "Turn Left",
      turnLeftMore: "Turn Left More",
      turnRight: "Turn Right",
      turnRightMore: "Turn Right More",
    },
    faceDetection: {
      blink: "Blink",
      turnHeadUp: "Turn Head Up",
      turnHeadDown: "Turn Head Down",
      turnHeadLeft: "Turn Head Left",
      turnHeadRight: "Turn Head Right",
      NOD: "Nod",
      openMouth: "Open Mouth",
      putFaceToCamera: "Please point your face to the camera",
      performActions: "Perform the following actions:",
    },
    langText: {
      "zh-hk": "EN",
      en: "CHT"
    },
    filesPicker: {
      title: "Click here to upload a file or image",
      noFile: "No Files"
    },
    contractScreen: {
      confirmSignture: "Signture Confirm",
      argeeContract: "I have read and agree to the contract。",
      previewContract: "Preview Contract"
    },
    error:{
      reqFailed: "Request Failed",
      sendFailed: "Send Failed",
      verifyFailed: "Verify Failed",
      inquireFailed: "Inquire Failed",
      submitFailed: "Submit Failed",
      loadPDFFailed: "Loading PFD Failed",
      loginFailed: "Login Failed",
      takePictureFailed: "Take Picture Failed"
    },
    inputError: {
      inputError: 'Input Error',
      pleCheckInput: "please check input",
      required: "*required",
      requiredAge18: "required age 18 or over",
      statementError: "you must be agreed above statement",
      email: "email format incorrect"
    },
    noPermission: {
      camera: "No Camera Permission",
      plsChangePermissionOnSetting: "Please change permission on setting"
    },
    userInfo: "userInfo",
    name: "name",
    permissions: "permissions",
    role: "role",
    permission: "permission",
    action: "action",
    save: "save",
    createdAt: "createdAt",
    updatedAt: "updatedAt",
    status: "status",
    active: "active",
    deleted: "deleted",
    disableLogin: "disableLogin",
    isSuperAdmin: "isSuperAdmin",
    supplementaryDocumentType: {
      NA: "",
      ID: "",
      ADDRESS: "",
      INCOME: "",
      BANK_STATEMENT: "BANK_STATEMENT"
    },
    receiptFileStatus: {
      SUBMIT: '提交',
      APPROVED: '已查看',
      REJECTED: '拒絕',
    },
    earlyRepaymentStatus: {
      "REQUEST": "REQUEST",
      "APPROVED": "APPROVED",
      "REJECTED": "REJECTED",
      "SUBMITED": "SUBMITED",
      "FINISHED": "FINISHED"
    },
    bookKeepingPeriodOptions: { 
      "weekly": "Weekly",
      "monthly": "Monthly",
      "quarterly": "Quarterly",
      "yearly": "Yearly"
    },
    bookKeepingPeriodInputOptions: { 
      "Monthly": "每月",
      "Weekly": "每週",
      "Quarterly": "每季",
      "Yearly": "每年"
    },
    bookKeepingPeriodDayOptions: {
      "32": "最後一日",
    },
    bookKeepingPeriodWeekOptions: { 
      "0": "星期日",
      "1": "星期1",
      "2": "星期2",
      "3": "星期3",
      "4": "星期4",
      "5": "星期5",
      "6": "星期6"
    },
    bookKeepingPeriodMonthOptions: {
      "1": "1月",
      "2": "2月",
      "3": "3月",
      "4": "4月",
      "5": "5月",
      "6": "6月",
      "7": "7月",
      "8": "8月",
      "9": "9月",
      "10": "10月",
      "11": "11月",
      "12": "12月",
    },
    week: "星期",
    month: "月",
    items: 'Items',
    description: 'Description',
    quantity: 'Qty.',
    unitPrice: 'U. Rate',
    amount: 'Amount',
    total: 'Total',
    subtotal: 'Subtotal',
    section: 'Section',
  }
});

const defaultWeekdays = ['週一', '週二', '週三', '週四', '週五', '週六', '週日']; // 默认星期文本

export default strings;
export { defaultWeekdays };