/*!
 *
 * Bryntum Gantt 5.0.1
 *
 * Copyright(c) 2022 Bryntum AB
 * https://bryntum.com/contact
 * https://bryntum.com/license
 *
 */
import{Widget as t,Rectangle as e,Tooltip as i}from"./Editor.js";class n extends t{static get $name(){return"Slider"}static get type(){return"slider"}static get configurable(){return{text:null,showValue:!0,showTooltip:!1,min:0,max:100,step:1,value:50,unit:null,thumbSize:20,tooltip:{$config:["lazy","nullify"],value:{type:"tooltip",align:"b-t",anchor:!1,axisLock:!0}},localizableProperties:["text"]}}compose(){const{id:t,min:e,max:i,showValue:n,step:l,text:a,value:u,unit:r="",readOnly:o,disabled:s}=this,h=`${t}-input`,p=Boolean(a||n);return{class:{"b-has-label":p,"b-text":p},children:{input:{tag:"input",type:"range",id:h,reference:"input",disabled:o||s?"":null,min:e,max:i,step:l,value:u,listeners:{input:"onInternalInput",change:"onInternalChange",mouseover:"onInternalMouseOver",mouseout:"onInternalMouseOut"}},label:{tag:"label",for:h,html:n?a?`${a} (${u}${r})`:u+r:a}}}}get focusElement(){return this.input}get percentProgress(){return(this.value-this.min)/(this.max-this.min)*100}onInternalChange(){this.updateUI(),this.triggerChange(!0),this.trigger("action",{value:this.value})}onInternalInput(){this.value=parseInt(this.input.value,10),this.trigger("input",{value:this.value})}onInternalMouseOver(){var t;const i=this,n=i.rtl?100-i.percentProgress:i.percentProgress;null===(t=i.tooltip)||void 0===t||t.showBy({target:e.from(i.input).inflate(i.thumbSize/2,-i.thumbSize/2),align:`b-t${Math.round(n)}`})}onInternalMouseOut(){var t;null===(t=this.tooltip)||void 0===t||t.hide()}triggerChange(t){this.triggerFieldChange({value:this.value,valid:!0,userAction:t})}updateMax(t){const e=this;e.input&&e._value>t&&(e.value=t,e.trigger("input",{value:e.value}))}updateMin(t){const e=this;e.input&&e._value<t&&(e.value=t,e.trigger("input",{value:e.value}))}changeTooltip(t,e){var n;return t&&(t.owner=this),this.showTooltip?i.reconfigure(e,t,{owner:this,defaults:{forElement:this.input,html:String(this.value)+(null!==(n=this.unit)&&void 0!==n?n:"")}}):null}updateValue(t){const e=this,{input:i,_tooltip:n}=e;var l;n&&(n.html=e.value+(null!==(l=e.unit)&&void 0!==l?l:""));i&&i.value!==String(t)&&(i.value=t,e.triggerChange(!1)),e.updateUI()}updateUI(){var t,i;const n=this;(null===(t=n._tooltip)||void 0===t?void 0:t.isVisible)&&(null===(i=n._tooltip)||void 0===i||i.alignTo({target:e.from(n.input).inflate(n.thumbSize/2,-n.thumbSize/2),align:`b-t${Math.round(n.percentProgress)}`}))}}n.initClass(),n._$name="Slider";export{n as Slider};
//# sourceMappingURL=Slider.js.map
