/*!
 *
 * Bryntum Gantt 5.0.1
 *
 * Copyright(c) 2022 Bryntum AB
 * https://bryntum.com/contact
 * https://bryntum.com/license
 *
 */
import{_defineProperty as e,Base as t,ObjectHelper as n,StringHelper as s}from"./Editor.js";var r=s=>{var r;return e(r=class extends(s||t){changeBreakpoints(e){return n.assertObject(e,"breakpoints"),null!=e&&e.width&&Object.keys(e.width).forEach((t=>{e.width[t].maxWidth=t})),null!=e&&e.height&&Object.keys(e.height).forEach((t=>{e.height[t].maxHeight=t})),e}updateBreakpoints(e){e&&(this.monitorResize=!0)}getBreakpoint(e,t){const n=Object.keys(e).map((e=>parseInt(e))).sort().find((e=>t<=e));return e[null!=n?n:e["*"]&&"*"]}activateBreakpoint(e,t){const n=this,s=n[`current${e}Breakpoint`];var r,i;t!==s&&(n[`current${e}Breakpoint`]=t,n.setConfig(t.configs),s&&n.element.classList.remove(`b-breakpoint-${s.name.toLowerCase()}`),n.element.classList.add(`b-breakpoint-${t.name.toLowerCase()}`),n.trigger(`responsive${e}Change`,{breakpoint:t,prevBreakpoint:s}),null===(r=t.callback)||void 0===r||r.call(t,{source:n,breakpoint:t,prevBreakpoint:s}),null===(i=n.recompose)||void 0===i||i.call(n))}applyResponsiveness(e,t){var n;const s=this,{width:r,height:i}=null!==(n=s.breakpoints)&&void 0!==n?n:{};if(r){const t=s.getBreakpoint(r,e);s.activateBreakpoint("Width",t)}if(i){const e=s.getBreakpoint(i,t);s.activateBreakpoint("Height",e)}}onInternalResize(e,t,n,s,r){super.onInternalResize(e,t,n,s,r),this.applyResponsiveness(t,n)}},"$name","Responsive"),e(r,"configurable",{breakpoints:null}),r},i=r=>{var i;return e(i=class extends(r||t){changeCssVarPrefix(e){return n.assertString(e,"prefix"),e&&!e.endsWith("-")&&(e+="-"),e||""}changeCss(e){n.assertObject(e,"css");const t=this;if(!globalThis.Proxy)throw new Error("Proxy not supported");const r=new Proxy({},{get(e,n){var r;return null===(r=getComputedStyle(t.element||document.documentElement).getPropertyValue(`--${t.cssVarPrefix}${s.hyphenate(n)}`))||void 0===r?void 0:r.trim()},set:(e,n,r)=>((t.element||document.documentElement).style.setProperty(`--${t.cssVarPrefix}${s.hyphenate(n)}`,r),!0)});return e&&(t._element?n.assign(r,e):t.$initialCSS=e),r}updateElement(e,...t){super.updateElement(e,...t),this.$initialCSS&&n.assign(this.css,this.$initialCSS)}get widgetClass(){}},"$name","Styleable"),e(i,"configurable",{cssVarPrefix:"",css:{}}),i};export{r as Responsive,i as Styleable};
//# sourceMappingURL=Styleable.js.map
